/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    ExpandContent: typeof import('./components/ExpandContent.vue')['default']
    ListContainer: typeof import('./components/client/ListContainer.vue')['default']
    ListFilters: typeof import('./components/client/ListFilters.vue')['default']
    ListItem: typeof import('./components/client/ListItem.vue')['default']
    PageBody: typeof import('./components/PageBody.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./components/form/SelectInput.vue')['default']
    SVGs: typeof import('./components/util/SVGs.vue')['default']
    TransitionExpand: typeof import('./components/TransitionExpand.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
  }
}
